src/Entity/Apuesta.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApuestaRepository")
 */
class Apuesta
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Porcentaje;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPorcentaje(): ?int
    {
        return $this->Porcentaje;
    }

    public function setPorcentaje(int $Porcentaje): self
    {
        $this->Porcentaje = $Porcentaje;

        return $this;
    }


}

src/Controller/RuletaController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Jugador;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Apuesta;
use App\Entity\Color;

class RuletaController extends AbstractController
{
    /**
     * @Route("/ruleta", name="ruleta")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $apuestas = $em->getRepository(Apuesta::class)->findAll();
        $colores = $em->getRepository(Color::class)->findAll();

        return $this->render('ruleta/index.html.twig', [
            'controller_name' => 'RuletaController',
            'apuestas' => $apuestas,
            'colores' => $colores
        ]);
    }

    /**
     *
     *
     * @Route("/IniciarSesion", name="iniciar_sesion", options={"expose" = true})
     * 
     */
    public function iniciarSesion (Request $request){
        $usuario = $request->get("usuario");
        $contraseña = $request->get("contraseña");
        $em = $this->getDoctrine()->getManager();
        $jugador = $em->getRepository(Jugador::class)->findOneBy(array('usuario' => $usuario));

        if ($jugador !== null && $jugador->getPassword() == $contraseña) {
            $jugador_response = (array("usuario" => $jugador->getUsuario(), "dinero" => $jugador->getDinero()));
            $response = new Response(\json_encode($jugador_response));
            $response->headers->set('Content-Type', 'application/json');
            return $response;
        } else {
            $response = new Response(-1);
            return $response;
        }
    }


    //     /**
    //  *
    //  *
    //  * @Route("/acabar_juego", name="acabar_juego", options={"expose" = true})
    //  * 
    //  */
    // public function acabarJuego(Request $request) {
    //     $jugadores = $request->get("jugadores");
    //     $data = json_decode($request->get("alias"));
    //     $data2 = json_decode($request->get("Totales"));
    //     if($data == null || $data2 == null){
    //         throw new Exception("no pasa");
    //     }
        
        
    //     $em = $this->getDoctrine()->getManager();
         
    //     for ($i = 0; $i < $jugadores ; $i ++) {
    //         $usuario = $data[$i];
    //         $dineroTotal = $data2[$i];
    //         $jugador = $em->getRepository(Jugador::class)->findOneBy(array('usuario' => $usuario));
    //         $jugador->setDinero($dineroTotal);
    //         $em->persist($jugador);
    //         $em->flush();
    //     }
    //     $response = new Response(1);
    //     $response->headers->set('Content-Type', 'application/json');
    //     return $response;
    // }

        /**
     *
     *
     * @Route("/CerrarSesion", name="cerrar_sesion", options={"expose" = true})
     * 
     */
    public function cerrarSesion (Request $request){
        $usuario = $request->get("usuario");
        $dinero = $request->get("dinero");
        $em = $this->getDoctrine()->getManager();
        $jugador = $em->getRepository(Jugador::class)->findOneBy(array('usuario' => $usuario));
        $jugador->setDinero((int)$dinero);
        $em->persist($jugador);
        $em->flush();
        $response = new Response(1);
        $response->headers->set('Content-Type', 'application/json');
        return $response;

    }
}

templates/ruleta/index.html.twig
{% extends 'base.html.twig' %}


{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" type="text/css" href="{{asset('ruleta/css/ruleta.css')}}">
{% endblock %}

{% block body %}
{{parent()}}
    <div class="container">
        <h1 class="text-center" > RULETA </h1>
    </div>
    <div class="container-fluid text-center">   
        <div class="col-md-5">
            <span class="glyphicon glyphicon-user"></span><label>JUGADOR 1</label>
            <input type="text" placeholder="usuario" id="jugador1">
            <input type="number" disabled="true" placeholder="Dinero" id="jugador1Dinero">
            <button id="jugador1ini" class="btn-primary" onclick="iniciarSesion('jugador1');" >iniciar sesion</button>
            <button id="jugador1clo" class="btn-primary" onclick="cerrarSesion('jugador1');" disabled="true">cerrar sesion</button>
            <select class="btn" id="jugador1Apuesta" disabled="true" onchange="EscogerColor('jugador1Apuesta');">
                <option>APUESTA</option>
                {% for color in colores%}
                <option>{{color.nombre}}</option>
                {% endfor %}
            </select>
            <select class="btn" onchange="Apostar('jugador1');" id="jugador1porcentaje" disabled true>
                <option value="default">PORCENTAJE</option>
                {% for apuesta in apuestas %}
                <option value="{{apuesta.porcentaje / 100}}">{{apuesta.porcentaje}}%</option>
                {% endfor %}
            </select>
            <button class="btn btn-danger" id="jugador1ALLIN" disabled="true">ALL IN</button>
        </div>

        <div class="col-md-5">
            <span class="glyphicon glyphicon-user"></span><label>JUGADOR 2</label>
            <input type="text" placeholder="usuario" id="jugador2" >
            <input type="number" disabled="true" placeholder="Dinero" id="jugador2Dinero">
            <button id="jugador2ini" class="btn-primary" onclick="iniciarSesion('jugador2');">iniciar sesion</button>
            <button id="jugador2clo" class="btn-primary" onclick="cerrarSesion('jugador2');"  disabled="true">cerrar sesion</button>
            <select class="btn" id="jugador2Apuesta" disabled="true" onchange="EscogerColor('jugador2Apuesta');">
                <option value="default">APUESTA</option>
                {% for color in colores%}
                <option>{{color.nombre}}</option>
                {% endfor %}
            </select>
            <select class="btn" id="jugador2porcentaje" onchange="Apostar('jugador2');" disabled="true">
                <option>PORCENTAJE</option>
                {% for apuesta in apuestas %}
                <option value="{{apuesta.porcentaje / 100}}">{{apuesta.porcentaje}}%</option>
                {% endfor %}
            </select>
            <button class="btn btn-danger" id="jugador2ALLIN" disabled="true">ALL IN</button>
        </div>
    </div>
    <div class="container col-lg-12 text-center row">
        <button class="btn btn-danger btn-group-lg" onclick="Ruleta();" id="ruleta" disabled="true">RULETA</button>
        <input type="number" id="monto" placeholder="TOTAL" disabled="true" value=0>  
        <button class="btn btn-group-lg btn-danger" onclick="AcabarJuego();" disabled="true" id="AcabarJuego">TERMINAR</button>
    </div>
    <div class="container-fluid text-center">
        <div class="col-md-5 text-center" >
            <span class="glyphicon glyphicon-user"></span><label>JUGADOR 3</label>
            <input type="text" placeholder="usuario" id="jugador3">
            <input type="number" disabled="true" placeholder="Dinero" id="jugador3Dinero">
            <button id="jugador3ini" class="btn-primary" onclick="iniciarSesion('jugador3');">iniciar sesion</button>
            <button id="jugador3clo" class="btn-primary" onclick="cerrarSesion('jugador3');" disabled="true">cerrar sesion</button>
            <select class="btn" id="jugador3Apuesta" disabled="true" onchange="EscogerColor('jugador3Apuesta')">
                <option >APUESTA</option>
                {% for color in colores%}
                <option>{{color.nombre}}</option>
                {% endfor %}
            </select>
            <select class="btn" id="jugador3porcentaje" onchange="Apostar('jugador3');" disabled="true">
                <option>PORCENTAJE</option>
                {% for apuesta in apuestas %}
                <option value="{{apuesta.porcentaje / 100}}">{{apuesta.porcentaje}}%</option>
                {% endfor %}
            </select>
            <button class="btn btn-danger" id="jugador3ALLIN" disabled="true">ALL IN</button>
        </div>
        <div class="col-md-5 text-center">
            <span class="glyphicon glyphicon-user"></span><label>JUGADOR 4</label>
            <input type="text" placeholder="usuario" id="jugador4">
            <input type="number" disabled="true" placeholder="Dinero" id="jugador4Dinero">
            <button id="jugador4ini" class="btn-primary" onclick="iniciarSesion('jugador4');">iniciar sesion</button>
            <button id="jugador4clo" class="btn-primary" onclick="cerrarSesion('jugador4');" disabled="true">cerrar sesion</button>
            <select class="btn" id="jugador4Apuesta" disabled="true" onchange="EscogerColor('jugador4Apuesta');">
                <option>APUESTA</option>
                {% for color in colores%}
                <option>{{color.nombre}}</option>
                {% endfor %}
            </select>
            <select class="btn" id="jugador4porcentaje" onchange="Apostar('jugador4');" disabled="true" >
                <option>PORCENTAJE</option>
                {% for apuesta in apuestas %}
                <option value="{{apuesta.porcentaje / 100}}">{{apuesta.porcentaje}}%</option>
                {% endfor %}
            </select>
            <button class="btn btn-danger" id="jugador4ALLIN" disabled="true">ALL IN</button>
        </div>
    </div>
{% endblock %}

{% block javascripts%}
{{ parent()}}
<script type="text/javascript" src="{{asset('ruleta/js/ruleta.js')}}"></script>
{%endblock%}